name: Android CI

on:
  push: 
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.MY_SSH_KEY }}
        submodules: true

  lookup:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.MY_SSH_KEY }}
        submodules: true
    - name: Copy GoogleServices JSON
      uses: canastro/copy-file-action@master
      with:
        source: "app/src/main/assets/tangem-app-config/android/google-services.json"
        target: "app/"

    - name: Fetch action
      id: pl
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "app/src/main/assets/tangem-app-config"
        type: ".json"
    
    - name: Fetch action app
      id: pl-app
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "app"
        type: ".json"

    - name: Output results
      run: |
        echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
        for i in ${{ steps.pl.outputs.paths }}; do
        echo $i
        done
    - name: Output results app
      run: |
        echo "Found ${{ steps.pl-app.outputs.path_count }} file(s) with this extension:"
        for i in ${{ steps.pl-app.outputs.paths }}; do
        echo $i
        done
